# fly.toml file generated for optimap on 2022-12-06T15:03:07+01:00

app = "optimap"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "sh release_command.sh"

[env]
  OPTIMAP_ALLOWED_HOST = "optimap.science,optimap.fly.dev"
  PORT = "8000"
  OPTIMAP_DEBUG = false
  OPTIMAP_EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
  OPTIMAP_EMAIL_HOST= "smtp.ionos.de"
  OPTIMAP_EMAIL_PORT_SMTP = "587"
  OPTIMAP_EMAIL_HOST_USER = "login@optimap.science"
  OPTIMAP_EMAIL_USE_TLS= true
  OPTIMAP_EMAIL_HOST_IMAP = "imap.ionos.de"
  OPTIMAP_EMAIL_PORT_IMAP = "993"
  OPTIMAP_EMAIL_IMAP_SENT_FOLDER = "\"Gesendete Objekte\""
  CSRF_TRUSTED_ORIGINS = "https://optimap.science"
  OPTIMAP_LOGGING_CONSOLE_LEVEL = "DEBUG"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
